[package]
name = "bloat_storage"
edition = "2024.beta"

[dependencies]
Sui = { local = "/home/femu/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
bloat_storage = "0x0"

[environments]
localnet = "9fd46431"
